language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  cd app
install:
  - yarn
script:
  - yarn lint
  - yarn compile
  - yarn test