language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

git:
  submodules: false

before_install:
  cd app

install:
  - yarn

script:
  - yarn lint
  - yarn compile
  # - yarn test

branches:
  only:
    - master